--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.1.22.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 10/7/2020 12:41:28 AM
-- Server version: 5.6.4-m7
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE pets_love;

--
-- Drop table `appoiments`
--
DROP TABLE IF EXISTS appoiments;

--
-- Drop table `shop`
--
DROP TABLE IF EXISTS shop;

--
-- Drop table `staf_data`
--
DROP TABLE IF EXISTS staf_data;

--
-- Drop table `users`
--
DROP TABLE IF EXISTS users;

--
-- Set default database
--
USE pets_love;

--
-- Create table `users`
--
CREATE TABLE users (
  id int(11) NOT NULL AUTO_INCREMENT,
  email varchar(100) NOT NULL,
  password varchar(100) NOT NULL,
  name varchar(100) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 2,
AVG_ROW_LENGTH = 16384,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

--
-- Create table `staf_data`
--
CREATE TABLE staf_data (
  id int(11) NOT NULL AUTO_INCREMENT,
  Name varchar(100) NOT NULL,
  `position` varchar(100) NOT NULL,
  image varchar(255) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 3,
AVG_ROW_LENGTH = 8192,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

--
-- Create table `shop`
--
CREATE TABLE shop (
  ID int(11) NOT NULL AUTO_INCREMENT,
  item_name varchar(100) NOT NULL,
  discription varchar(255) NOT NULL,
  itemImage varchar(255) NOT NULL,
  item_price double NOT NULL,
  quntity int(11) NOT NULL,
  PRIMARY KEY (ID)
)
ENGINE = INNODB,
AUTO_INCREMENT = 3,
AVG_ROW_LENGTH = 8192,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

--
-- Create table `appoiments`
--
CREATE TABLE appoiments (
  id int(11) NOT NULL AUTO_INCREMENT,
  f_name varchar(50) NOT NULL,
  l_name varchar(50) NOT NULL,
  phone varchar(15) NOT NULL,
  email varchar(50) NOT NULL,
  date date NOT NULL,
  create_date date NOT NULL,
  animal_type varchar(50) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 10,
AVG_ROW_LENGTH = 8192,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

-- 
-- Dumping data for table users
--
INSERT INTO users VALUES
(1, 'shan@g.com', '123', 'shan');

-- 
-- Dumping data for table staf_data
--
INSERT INTO staf_data VALUES
(1, 'mr. ABC ', 'Doctor', '497333.jpg'),
(2, 'salitha', 'doc', '497333.jpg');

-- 
-- Dumping data for table shop
--
INSERT INTO shop VALUES
(2, 'dada', 'aaaaa', '1588004448.jpg', 12356, 123456);

-- 
-- Dumping data for table appoiments
--
INSERT INTO appoiments VALUES
(9, 'Buddhika', 'Pathiraja', '0716017460', 'prasadh.pathiraja@gmail.com', '2020-04-30', '2020-04-27', 'cat');

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;